INSERT INTO jmp_field(name,fieldname,jgetname,siteid,orderid,fieldtype,fieldlength,showlist) VALUES('标题','title',{title},{siteid},1,2,255,1);
INSERT INTO jmp_field(name,fieldname,jgetname,siteid,orderid,fieldtype,fieldlength,showlist) VALUES('URL','url','网页URL',{siteid},2,2,600,1);
INSERT INTO jmp_field(name,fieldname,jgetname,siteid,orderid,fieldtype,fieldlength,showlist) VALUES('发布时间','syntime','发布时间',{siteid},3,2,30,1);
INSERT INTO jmp_field(name,fieldname,jgetname,siteid,orderid,fieldtype,fieldlength,showlist) VALUES('来源','source','来源',{siteid},4,2,255,1);
INSERT INTO jmp_field(name,fieldname,jgetname,siteid,orderid,fieldtype,fieldlength,showlist) VALUES('内容','content',{content},{siteid},5,2,3000,0);
INSERT INTO jmp_field(name,fieldname,jgetname,siteid,orderid,fieldtype,fieldlength,showlist) VALUES('作者','author','作者',{siteid},6,2,255,1);
INSERT INTO jmp_field(name,fieldname,jgetname,siteid,orderid,fieldtype,fieldlength,showlist) VALUES('视频','video','视频',{siteid},7,2,255,1);
INSERT INTO jmp_field(name,fieldname,jgetname,siteid,orderid,fieldtype,fieldlength,showlist) VALUES('摘要','abstract','摘要',{siteid},8,2,255,1);
INSERT INTO jmp_field(name,fieldname,jgetname,siteid,orderid,fieldtype,fieldlength,showlist) VALUES('副标题','subtitle','副标题',{siteid},9,2,255,1);